#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("XamPaperScissorsRock.Resource", IsApplication=true)]

namespace XamPaperScissorsRock
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F010000
			public const int lose = 2130771968;
			
			// aapt resource value: 0x7F010001
			public const int PSR = 2130771969;
			
			// aapt resource value: 0x7F010002
			public const int win = 2130771970;
			
			// aapt resource value: 0x7F010003
			public const int ww2 = 2130771971;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F020000
			public const int btnNext = 2130837504;
			
			// aapt resource value: 0x7F020001
			public const int btnPlay = 2130837505;
			
			// aapt resource value: 0x7F020002
			public const int etEnterName = 2130837506;
			
			// aapt resource value: 0x7F020003
			public const int imageAnswer = 2130837507;
			
			// aapt resource value: 0x7F020004
			public const int imgMainPic = 2130837508;
			
			// aapt resource value: 0x7F020005
			public const int linearLayout1 = 2130837509;
			
			// aapt resource value: 0x7F020006
			public const int radio_paper = 2130837510;
			
			// aapt resource value: 0x7F020007
			public const int radio_rock = 2130837511;
			
			// aapt resource value: 0x7F020008
			public const int radio_scissors = 2130837512;
			
			// aapt resource value: 0x7F020009
			public const int tvEnterName = 2130837513;
			
			// aapt resource value: 0x7F02000A
			public const int tvMessage = 2130837514;
			
			// aapt resource value: 0x7F02000B
			public const int tvName = 2130837515;
			
			// aapt resource value: 0x7F02000C
			public const int tvTitle = 2130837516;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F030000
			public const int Game = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int Main = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F040000
			public const int app_name = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
